import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Button, buttonVariants } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import Link from "next/link";

export default function Home() {
  const dbNames = ["teachers", "students"];
  return (
    <>
      <Head>
        <title>School Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="w-1/2  flex justify-evenly">
        {dbNames.map((dbName, index) => {
          return (
            <Link
              key={index}
              className={buttonVariants() + " capitalize"}
              href={`/${dbName}`}
            >
              {dbName}
            </Link>
          );
        })}
      </div>
    </>
  );
}
